### ISSUE TITLE
Slash commands aren't refreshing

### ISSUE THREAD

**Issue by nonlooped** [KingOKarma/discord.js-v13TS-template#2]
The bot logs: 
```
BotName#0000 is online!
[]
Started refreshing application (/) commands
Sucessfully reloaded application (/) commands.
```
But doesn't actually refresh (/) commands. It still shows the / commands from my old javascript code. And it doesn't show the ones that come with the bot like "say" and "dev". I haven't changed anything in the code

**Comment by KingOKarma** [comment]
I'm still seeing if there's a way around fixing this but discord refreshing global commands takes longer than refreshing guild commands, Although I have learnt that refreshing guild's commands is instant compared to the 1 hour or so wait for global commands to refresh.
This project is still on going with updates so I'm working on fixing whatever I can!

**Comment by nonlooped** [comment]
> I'm still seeing if there's a way around fixing this but discord refreshing global commands takes longer than refreshing guild commands, Although I have learnt that refreshing guild's commands is instant compared to the 1 hour or so wait for global commands to refresh.
> This project is still on going with updates so I'm working on fixing whatever I can!

I'd recommend you don't use global commands. Guild commands are better and as you said, refresh instantly. I use guild commands on another project and it runs smoothly.

**Comment by KingOKarma** [comment]
Ye that was the plan, I'm currently busy with some life things but feel free to create a pull request if you want, If not I'll get on switching it to guild commands as soon as I can, I'll likely make it a system where you can use guild commands on development and global commands when pushing to production
